name: CI/CD

on: [push, pull_request]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
            submodules: recursive

      - name: Install MPI
        run: sudo apt-get update && sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev 

      - name: Verify MPI installation
        run: mpirun --version  
      
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run:
          cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run Test
        run: cd /home/runner/work/Lentini-Lacagnina/Lentini-Lacagnina/build && ./test_multiplication

      - name: Install Dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y \
         autoconf \
         automake \
         cryptsetup \
         fuse \
         fuse2fs \
         git \
         libfuse-dev \
         libglib2.0-dev \
         libseccomp-dev \
         libtool \
         pkg-config \
         runc \
         squashfs-tools \
         squashfs-tools-ng \
         uidmap \
         wget \
         zlib1g-dev
    
      - name: Install Singularity
        run: wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce_4.1.3-jammy_amd64.deb && sudo dpkg -i singularity-ce_4.1.3-jammy_amd64.deb

      - name: Build Singularity Container
        run: sudo singularity build matrix_multi.sif singularity.def
        
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install sshpass    
      
      - name: Submit Job to Cluster
        run: sshpass -p "${{ secrets.CINECA_PASSWORD }}" scp -o StrictHostKeyChecking=no matrix_multi.sif job.sh a08trb55@login.g100.cineca.it:/g100/home/usertrain/a08trb55/

      - name: Wait for Job Completion
        run: |
          sleep 60  # Wait for the job to complete. Adjust the time as needed.

      - name: Retrieve Output Files
        run: |
          sshpass -p "${{ secrets.CINECA_PASSWORD }}" scp -o StrictHostKeyChecking=no a08trb55@login.g100.cineca.it:/g100/home/usertrain/a08trb55/slurmout.txt .
          sshpass -p "${{ secrets.CINECA_PASSWORD }}" scp -o StrictHostKeyChecking=no a08trb55@login.g100.cineca.it:/g100/home/usertrain/a08trb55/slurmerr.txt .

      - name: Commit and Push Output Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add slurmout.txt slurmerr.txt
          git commit -m "Add output and error files from cluster"
          git push
